version: "3.8"

services:
  fastapi-service:
    build: .
    container_name: test-task-trek-II-megaschool-itmo
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      - TZ=UTC
    volumes:
      - ./logs:/app/logs
  nginx:
    ports:
      - "80:80"
      - "443:443"
    networks:
      - backend
networks:
  backend:
    driver: bridge
